# -*- coding: utf-8 -*-
"""APM466H1/MAT1856H1 Assignment #1 Data Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCYtYmExgO7-iXjSc_2Pj87BsRBJGZnp

# Markets Insider Canadian Government Bond Data Extraction and Plotting
### Created and Maintained by Jaspreet Khela

Note: You need to run this notebook to generate the CSV files in the Google Colab filesystem (on the left side). Please double check the data in the CSV files against official sources to ensure data collection accuracy.

## Markets Insider Bond Data Extraction Script: Overview and Disclaimer

### Overview

This script programmatically extracts **Canadian government bond data** from Markets Insider and produces:

1. **Bond metadata**  
   Parsed directly from each bond’s “Bond Data” HTML table, including:
   - ISIN  
   - Name  
   - Issuer  
   - Country  
   - Currency  
   - Issue price and issue date  
   - Coupon rate and payment characteristics  
   - Maturity date and coupon schedule  

2. **Historical closing prices**  
   Retrieved via Markets Insider’s internal `Chart_GetChartData` JSON endpoint using the bond’s `tkData` identifier.  
   The script:
   - Extracts raw time series points from nested JSON structures  
   - Converts timestamps into calendar dates  
   - Filters observations to **weekdays only**  
   - Restricts data to a **single, user-defined date window**

3. **Bond classification**  
   Each bond is classified as:
   - **Short-term** if it matures within three years of the configured start date  
   - **Long-term** otherwise  

4. **Per-bond outputs**
   For each bond, the script:
   - Displays a clearly labeled dataframe in Google Colab (preceded by a readable bond title)  
   - Exports **one CSV file per bond** containing its full cleaned dataset  
   - Generates two plots:
     - Closing price over time (percent of par)  
     - Daily log returns  

5. **Master dataset**
   A single **root master CSV** is generated that vertically concatenates all individual bond dataframes.  
   This master file contains the same columns as the per-bond CSVs and is intended for downstream analysis or archiving.

### Design principles

- **Single source of truth for dates**  
  The start and end dates are defined once at the top of the script and automatically applied to all bonds.

- **Minimal redundancy**  
  Only essential identifiers are retained in each row. Redundant repeated identifiers have been removed to keep tables compact while preserving documentation URLs.

- **Maintainability**
  - Modular helper functions for parsing, filtering, classification, and plotting  
  - Extensive inline comments explaining purpose and assumptions  
  - No reliance on browser automation or fragile DOM event hooks  

### Disclaimer

- **Date range input required**  
  The script requires the user to explicitly specify the start and end dates at the top of the file. Results are strictly limited to this window.

- **Unofficial data source**  
  Markets Insider does not provide a documented public API for this data. The script relies on observed HTML structure and internal JSON endpoints, which may change without notice.

- **Verification strongly recommended**  
  All scraped data should be cross-checked against official sources (e.g., Government of Canada publications or primary dealer data) before being used for academic, financial, or professional purposes.

Use this script as a **data collection aid**, not as an authoritative source of record.


### Contact

Contact jaspreet.khela@mail.utoronto.ca or visit https://jaspreetkhela.github.io/JaspreetKhela/ to get in touch! Enjoy :)

## Canadian Bonds Data Scraper Script
"""

"""
Markets Insider Bond Data Pipeline

Features
--------
1. Scrapes static bond metadata from Markets Insider bond pages:
   - ISIN, name, issuer, country
   - Issue details (volume, currency, price, date)
   - Coupon structure and payment characteristics
   - Maturity information

2. Retrieves historical bond closing prices using the Chart_GetChartData endpoint
   identified by tkData.

3. Uses a single, centralized date configuration to:
   - Control API request windows
   - Filter observations to a consistent analysis period
   - Restrict data to weekday trading days

4. Classifies bonds as:
   - Short-term: maturity within 3 years of START_DATE
   - Long-term: maturity beyond 3 years of START_DATE

5. Produces one root-level master CSV containing the union of all per-bond CSV rows:
   - bonds_master_all.csv
   - One row per bond-day, with full bond metadata repeated per row.
   - Column order matches the Bond Data table with Close Price at the end.

6. Produces one self-contained CSV per bond (stored under ./bonds/):
   - Full bond metadata repeated per date
   - Closing prices appended as the final column

7. For each bond:
   - Prints a readable bond title before displaying the bond dataframe
   - Displays the bond dataframe
   - Generates two plots:
       a) daily closing prices (% of par)
       b) daily log returns (unitless)

8. Ensures input bond uniqueness by:
   - Deduplicating on tkData (time series identifier)
   - Secondary deduplication on bond page URL

9. Uses explicit HTTP headers and request timeouts to ensure:
   - Stable HTML parsing
   - Consistent API responses
   - Predictable failure behavior in batch execution

URLs are kept for documentation:
  - bond_page_url
  - chart_json_url

Dependencies
------------
beautifulsoup4
pandas
numpy
matplotlib
requests
"""

import os
import re
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from bs4 import BeautifulSoup
from urllib.parse import unquote


# ======================================================================================
# 1) Date configuration (single source of truth)
# ======================================================================================
START_DATE = pd.to_datetime("2026-01-05")  # inclusive
END_DATE   = pd.to_datetime("2026-01-19")  # inclusive

FROM_YYYYMMDD = START_DATE.strftime("%Y%m%d")
TO_YYYYMMDD   = END_DATE.strftime("%Y%m%d")

START = START_DATE.date()
END   = END_DATE.date()


# ======================================================================================
# 2) HTTP settings
# ======================================================================================
HEADERS = {"User-Agent": "Mozilla/5.0"}
TIMEOUT_SEC = 30


# ======================================================================================
# 3) Bond inputs (bond_page_url, chart_json_url used only to extract tkData)
#    Includes updated 30 and 32 values.
# ======================================================================================
RAW_BONDS = [
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202326-bond-2026-ca135087r226?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C130654501%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202026-bond-2026-ca135087l518?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C57601476%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202326-bond-2026-ca135087p816?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C124578091%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202426-bond-2026-ca135087r556?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C132969994%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_201526-bond-2026-ca135087e679?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C28975906%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202426-bond-2026-ca135087r978?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C135402145%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202126-bond-2026-ca135087l930?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C111141014%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202426-bond-2026-ca135087s398?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C137893857%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202427-bond-2027-ca135087s547?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C139591564%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202127-bond-2027-ca135087m847?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C114329463%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202527-bond-2027-ca135087s885?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C142700048%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_201627-bond-2027-ca135087f825?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C33461441%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/8_000-canada-government-of-bond-2027-ca135087vw17?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C490501%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202527-bond-2027-ca135087t461?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C145462038%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202227-bond-2027-ca135087p733?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C123653782%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202227-bond-2027-ca135087n837?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C119036843%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202527-bond-2027-ca135087t610?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C148260836%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202528-bond-2028-ca135087t958?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C151027258%2C16%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202228-bond-2028-ca135087p576?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C122651336%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_201728-bond-2028-ca135087h235?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C37720230%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202328-bond-2028-ca135087q491?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C126528699%2C1330%2C184&from=20251115&to=20260115"),

    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202532-bond-2032-ca135087s968?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C142567197%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202030_series_l443-bond-2030-ca135087l443?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C57501684%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/5_750-canada-government-of-bond-2029-ca135087wl43?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C847359%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202229-bond-2029-ca135087n670?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C117855494%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202434-bond-2034-ca135087r713?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C133356706%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202430-bond-2030-ca135087s471?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C138913105%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202429-bond-2029-ca135087r895?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C134387959%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202531-bond-2031-ca135087t792?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C149759344%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202131-bond-2031-ca135087m276?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C111293704%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202131-bond-2031-ca135087n266?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C114466942%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202535-bond-2035-ca135087t537?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C146822867%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202530-bond-2030-ca135087t388?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C144389623%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202334-bond-2034-ca135087r481?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C131843886%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202232-bond-2032-ca135087p329?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C120914999%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/5_750-canada-government-of-bond-2033-ca135087xg49?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C1321208%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202329-bond-2029-ca135087q988?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C130328741%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202333-bond-2033-ca135087q723?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C128007448%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202232-bond-2032-ca135087n597?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C117606959%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202434-bond-2034-ca135087s216?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C136888775%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_202535-bond-2035-ca135087s620?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C141608780%2C1330%2C184&from=20251115&to=20260115"),
    ("https://markets.businessinsider.com/bonds/canadacd-bonds_201829-bond-2029-ca135087j397?miRedirects=1",
     "https://markets.businessinsider.com/Ajax/Chart_GetChartData?instrumentType=Bond&tkData=1%2C42965744%2C1330%2C184&from=20251115&to=20260115")
]


# ======================================================================================
# 4) Build BONDS list (bond_page_url + tkData) and deduplicate for uniqueness
# ======================================================================================
def extract_tkdata(chart_json_url: str) -> str:
    u = unquote(chart_json_url)
    m = re.search(r"(?:\?|&)tkData=([^&]+)", u)
    if not m:
        raise ValueError("tkData not found in chart_json_url")
    return m.group(1)


bond_records = []
for bond_page_url, chart_json_url in RAW_BONDS:
    bond_records.append({"bond_page_url": bond_page_url, "tkData": extract_tkdata(chart_json_url)})

df_input = pd.DataFrame(bond_records)

df_unique = df_input.drop_duplicates(subset=["tkData"], keep="first").copy()
df_unique = df_unique.drop_duplicates(subset=["bond_page_url"], keep="first").copy()

BONDS = df_unique.to_dict(orient="records")


# ======================================================================================
# 5) Working-code helper functions (aligned with proven version)
# ======================================================================================
def isin_from_bond_url(url: str) -> str | None:
    m = re.search(r"\b(ca[0-9a-z]{10})\b", url, re.I)
    return m.group(1).upper() if m else None


def chart_url_for_tkdata(tkdata: str) -> str:
    return (
        "https://markets.businessinsider.com/Ajax/Chart_GetChartData"
        f"?instrumentType=Bond&tkData={tkdata}&from={FROM_YYYYMMDD}&to={TO_YYYYMMDD}"
    )


def iter_points(obj):
    if isinstance(obj, list):
        if obj and all(isinstance(x, list) and len(x) >= 2 for x in obj):
            for x in obj:
                yield x[0], x[1]
        for x in obj:
            yield from iter_points(x)
    elif isinstance(obj, dict):
        keys = {str(k).lower(): k for k in obj.keys()}
        tkey = next((keys[k] for k in ["x", "t", "time", "date", "timestamp"] if k in keys), None)
        vkey = next((keys[k] for k in ["y", "v", "value", "close", "price", "last"] if k in keys), None)
        if tkey and vkey:
            yield obj[tkey], obj[vkey]
        for v in obj.values():
            yield from iter_points(v)


def to_date(t):
    if isinstance(t, str):
        dt = pd.to_datetime(t, errors="coerce")
        return None if pd.isna(dt) else dt.date()
    try:
        t = float(t)
    except Exception:
        return None
    unit = "ms" if t > 1e11 else "s"
    dt = pd.to_datetime(t, unit=unit, errors="coerce")
    return None if pd.isna(dt) else dt.date()


def filter_window_weekdays(df: pd.DataFrame) -> pd.DataFrame:
    df = df[(df["date"] >= START) & (df["date"] <= END)]
    df = df[[pd.to_datetime(d).weekday() < 5 for d in df["date"]]]
    return df


def fetch_bond_info(bond_page_url: str) -> dict:
    html = requests.get(bond_page_url, headers=HEADERS, timeout=TIMEOUT_SEC).text
    soup = BeautifulSoup(html, "html.parser")

    # NOTE: ISIN_from_url is intentionally NOT included in the output dict
    # to satisfy the requirement to remove that redundant column.
    out = {"bond_page_url": bond_page_url}

    tbody = soup.select_one("tbody.table__tbody")
    if not tbody:
        return out

    current_group = None
    for tr in tbody.select("tr.table__tr"):
        tds = tr.select("td.table__td")
        if not tds:
            continue

        if len(tds) == 1 and "group" in (tds[0].get("class") or []):
            current_group = tds[0].get_text(" ", strip=True)
            continue

        if len(tds) >= 2:
            key = tds[0].get_text(" ", strip=True)
            val = tds[1].get_text(" ", strip=True)

            final_key = key
            if final_key in out and current_group:
                final_key = f"{current_group}::{key}"
            elif final_key in out:
                final_key = f"{key}__2"

            val_norm = val.replace("\xa0", " ").strip()
            if re.fullmatch(r"-?\d+,\d+", val_norm):
                val_norm = val_norm.replace(",", ".")
            out[final_key] = val_norm

    if "ISIN" in out and isinstance(out["ISIN"], str):
        out["ISIN"] = out["ISIN"].strip().upper()

    return out


def classify_term(maturity_date_str: str) -> str:
    maturity = pd.to_datetime(maturity_date_str, errors="coerce")
    if pd.isna(maturity):
        return "Unknown-term"
    years = (maturity.date() - START).days / 365.25
    return "Short-term" if years <= 3.0 else "Long-term"


def safe_filename(s: str) -> str:
    s = s.strip().replace(" ", "_")
    s = re.sub(r"[^A-Za-z0-9_\-\.]+", "", s)
    return s


def bond_title_from_row(df_row: pd.Series) -> str:
    """
    Create a readable bond title for Colab output and plot titles without using bond_label.
    Uses fields already present in the table.
    """
    term = df_row.get("Term", "Unknown-term")
    name = df_row.get("Name", "")
    coupon = df_row.get("Coupon", "")
    mat = df_row.get("Maturity Date", "")
    isin = df_row.get("ISIN", "")

    parts = [term]
    if isinstance(name, str) and name:
        parts.append(name)
    if isinstance(coupon, str) and coupon:
        parts.append(coupon)
    if isinstance(mat, str) and mat:
        parts.append(f"Mat {mat}")
    if isinstance(isin, str) and isin:
        parts.append(isin)

    return " | ".join(parts)


# ======================================================================================
# 6) Data collection loop (working structure, with bond_label removed)
# ======================================================================================
info_rows = []
price_rows = []
errors = []

for bond in BONDS:
    bond_page_url = bond["bond_page_url"]
    tkdata = bond["tkData"]
    chart_url = chart_url_for_tkdata(tkdata)

    info = fetch_bond_info(bond_page_url)
    info["tkData"] = tkdata
    info["chart_json_url"] = chart_url

    # ISIN: prefer table ISIN; fallback to URL ISIN only internally
    if "ISIN" not in info or not isinstance(info["ISIN"], str) or not info["ISIN"].strip():
        info["ISIN"] = isin_from_bond_url(bond_page_url)

    info["Term"] = classify_term(info.get("Maturity Date", ""))
    info_rows.append(info)

    try:
        resp = requests.get(chart_url, headers=HEADERS, timeout=TIMEOUT_SEC)
        resp.raise_for_status()
        data = resp.json()

        pts = []
        for t, v in iter_points(data):
            d = to_date(t)
            if d is None:
                continue
            try:
                val = float(v)
            except Exception:
                continue
            pts.append((d, val))

        if not pts:
            raise RuntimeError("No time-series points parsed from Chart_GetChartData.")

        df = pd.DataFrame(pts, columns=["date", "Close Price (% of par)"])
        df = df.groupby("date", as_index=False)["Close Price (% of par)"].last().sort_values("date")
        df = filter_window_weekdays(df)

        df.insert(0, "ISIN", info["ISIN"])
        df.insert(1, "tkData", tkdata)
        df.insert(2, "bond_page_url", bond_page_url)
        df.insert(3, "chart_json_url", chart_url)

        price_rows.append(df)

    except Exception as e:
        errors.append((bond_page_url, str(e)))


# ======================================================================================
# 7) Merge, column ordering, master export
#    Master is the union of per-bond CSV rows.
# ======================================================================================
df_info = pd.DataFrame(info_rows).drop_duplicates(subset=["bond_page_url", "tkData"])

df_prices = pd.concat(price_rows, ignore_index=True) if price_rows else pd.DataFrame(
    columns=["ISIN", "tkData", "bond_page_url", "chart_json_url", "date", "Close Price (% of par)"]
)

df_all = df_prices.merge(df_info, on=["ISIN", "tkData", "bond_page_url", "chart_json_url"], how="left")

# Column order with Close at the end
BOND_DATA_ORDER = [
    "ISIN",
    "Name",
    "Country",
    "Issuer",
    "Issue Volume",
    "Currency",
    "Issue Price",
    "Issue Date",
    "Coupon",
    "Denomination",
    "Quotation Type",
    "Payment Type",
    "Special Coupon Type",
    "Maturity Date",
    "Coupon Payment Date",
    "Payment Frequency",
    "No. of Payments per Year",
    "Coupon Start Date",
    "Final Coupon Date",
    "Floater?",
]

preferred = (
    ["Term", "bond_page_url", "tkData", "chart_json_url"]
    + [c for c in BOND_DATA_ORDER if c in df_all.columns]
    + ["date", "Close Price (% of par)"]
)

remaining = [c for c in df_all.columns if c not in preferred]
final_cols = [c for c in preferred if c in df_all.columns] + remaining
final_cols = [c for c in final_cols if c != "Close Price (% of par)"] + (
    ["Close Price (% of par)"] if "Close Price (% of par)" in df_all.columns else []
)

df_all = df_all[final_cols]

# Root master CSV: union of all per-bond rows
df_all.to_csv("bonds_master_all.csv", index=False)
print("Root master CSV written: bonds_master_all.csv")

if errors:
    print("\nErrors during time series retrieval:")
    for u, msg in errors:
        print(" ", u, "->", msg)


# ======================================================================================
# 8) Per-bond display, per-bond CSV export, and per-bond plots
# ======================================================================================
out_dir = "bonds"
os.makedirs(out_dir, exist_ok=True)

for (isin, tkdata), bond_df in df_all.groupby(["ISIN", "tkData"]):
    bond_df = bond_df.sort_values("date").copy()

    # Create a bond title without bond_label
    title = bond_title_from_row(bond_df.iloc[0])

    # Title block for readability in Colab output
    print("\n" + "=" * 120)
    print(f"BOND: {title}")
    print("=" * 120)

    # Display dataframe before plots
    display(bond_df)

    # Export per-bond CSV (full dataframe slice)
    term = bond_df["Term"].iloc[0] if "Term" in bond_df.columns else "Unknown-term"
    term_safe = str(term).replace(" ", "_")
    key = isin if isinstance(isin, str) and isin.strip() else f"tkData_{tkdata.replace(',', '_')}"
    csv_name = safe_filename(f"{term_safe}_{key}.csv")
    csv_path = os.path.join(out_dir, csv_name)
    bond_df.to_csv(csv_path, index=False)

    # Plot: Close Price
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(pd.to_datetime(bond_df["date"]), bond_df["Close Price (% of par)"])
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=1))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    fig.autofmt_xdate(rotation=30)
    ax.set_title(f"Bond Closing Prices from {START} to {END} for {title}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Close Price (% of par)")
    plt.tight_layout()
    plt.show()

    # Plot: Log Returns
    bond_df["Log Return (unitless)"] = np.log(
        bond_df["Close Price (% of par)"] / bond_df["Close Price (% of par)"].shift(1)
    )

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(pd.to_datetime(bond_df["date"]), bond_df["Log Return (unitless)"])
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=1))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    fig.autofmt_xdate(rotation=30)
    ax.set_title(f"Daily Log Returns from {START} to {END} for {title}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Log Return (unitless)")
    plt.tight_layout()
    plt.show()

print(f"\nPer-bond CSVs written to ./{out_dir}/")
print(f"Unique bonds processed: {df_all.groupby(['ISIN','tkData']).ngroups}")